import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { CityProvider } from "./context/CityContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Weather App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <CityProvider>
         <html lang="en" suppressHydrationWarning className="transition-all duration-500 ease-in-out">
            <body className={inter.className} suppressHydrationWarning={true}>
               <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange>
                  {children}
               </ThemeProvider>
            </body>
         </html>
      </CityProvider>
   );
}
